/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_viaplay_ime_jni_ScreenShot */

#ifndef _Included_com_viaplay_ime_jni_ScreenShot
#define _Included_com_viaplay_ime_jni_ScreenShot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_viaplay_ime_jni_ScreenShot
 * Method:    getScreenShot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_viaplay_ime_jni_ScreenShot_getScreenShot
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
